version: 40
jobs:
- name: Build Docker Image
  steps:
  - !CheckoutStep
    name: Checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: SUCCESSFUL
    optional: false
  - !BuildImageStep
    name: Build Image
    output: !RegistryOutput
      tags: '@server@/rapid/host:latest'
    condition: SUCCESSFUL
    optional: false
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
